/* eslint-disable @next/next/no-page-custom-font */
import { useTheme } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import Page from "../components/Page";
import Section from "../components/Section";
import About from "../section/home/About";
import Footer from "../section/home/Footer";
import Header from "../section/home/Header";
import Main from "../section/home/Main";
import Skills from "../section/home/Skills";

const Home: NextPage = function Home() {
  const theme = useTheme();
  return (
    <Page>
      <Head>
        <title>Wildan Najah Wildiansyah</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Section>
        <Header />
        <Main />
      </Section>
      <Section title="About Me" subtitle="My Introduction">
        <About />
      </Section>
      <Section title="Skills" subtitle="My Technical Skills">
        <Skills />
      </Section>
      <Section
        sx={{
          marginTop: "2rem",
          padding: "2rem",
          fontSize: "3rem",
          bottom: 0,
          backgroundColor: theme.palette.background.paper,
        }}
      >
        <Footer />
      </Section>
    </Page>
  );
};

export default Home;
